title: "Jojobe"
author: "J. M. Nidel"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page # false = don't put blog on home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Hello!"}
  - {title: "Contact me, maybe?"}

  #- {file: "index.html"}
  #- {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jnidel@uwo.ca"}
  - {title: Github, icon: github, url: "https://github.com/jmnidel"}
  - {title: Twitter, icon: twitter, url: "https://old.reddit.com"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
